# Helium

hide_ascii      = false
spacing         = 2
padding         = 0
separator       = "->"
key_color       = "Blue"
separator_color = "#e12885"

[bar]
glyph           = "o"
symbol_open     = "("
symbol_close    = ")"
hide_delimiters = false
visible         = true

[box]
title           = " Mikuwu "
border          = "rounded"
visible         = false

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "#86cecb"
path		= "~/.config/ascii/miku2-ansi.txt"

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
kernel          = "Kern."
battery         = "Bat."
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Dist."
terminal        = "Term."
shell           = "Shell"
packages        = "Pkgs"
uptime          = "Up"
memory          = "Mem."
machine         = "Mach."
resolution      = "Resol."
cpu             = "CPU"
gpu             = "GPU"
